Data validations and unit tests
Reggeditt/blog-rails pull request #4
Opened 2023-08-18 11:14 UTC by Reggeditt

## In this pull request, I;

- Add the following validations:
    - For the User model:
Name must not be blank.
PostsCounter must be an integer greater than or equal to zero.
    - For the Post model:
Title must not be blank.
Title must not exceed 250 characters.
CommentsCounter must be an integer greater than or equal to zero.
LikesCounter must be an integer greater than or equal to zero.

- Add unit specs for all models' methods and validations.

2023-08-18 14:51 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi @Reggeditt  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media2.giphy.com/media/RjQ68u1NIlcL47cCN0/giphy.gif"/>

## Highlights :fire: 
- All required user validations added :heavy_check_mark: 
- All required posts validations added :heavy_check_mark: 
- Has unit tests for `User`, `Post`, `Comment`, and `Like` model :heavy_check_mark: 
- All tests passing :heavy_check_mark: 
- Most model specs has **Validation** tests :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-18 14:51 UTC, NahnahAJ commented on app/models/user.rb
> +  end
- [ ] Great job so far @Reggeditt  There are just a few changes I will suggest you implement and you'll be on your way to the next milestone :+1: 
- [ ] Per the project requirements, you were asked to `Add unit specs for all of your models' methods and validations` You have done an amazing job adding most of the tests. I noticed that this `recent_posts` method hasn't been tested yet. So kindly include that in your tests :wink:

2023-08-18 14:51 UTC, NahnahAJ commented on app/models/post.rb
> +  end
- [ ] Kindly add `unit specs` for this `recent_comments` method as well :+1:

2023-08-18 14:51 UTC, NahnahAJ commented on app/models/post.rb
> +  end
- [ ] Kindly add `unit specs` for this `update_comments_counter` and `update_likes_counter` method as well :+1:

2023-08-18 14:51 UTC, NahnahAJ commented on spec/models/post_spec.rb
> +end
- [ ] I also noticed that your tests don't contain tests for these two validations below in your Post Model in the  `post.rb` file so kindly include those as well :+1: 

```ruby
 validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

```

2023-08-18 14:51 UTC, NahnahAJ commented on app/models/like.rb
> +  end
- [ ] Kindly add `unit specs` for this `update_post_likes_counter` method as well :+1:

2023-08-18 14:51 UTC, NahnahAJ commented on app/models/comment.rb
> +  end
- [ ] Kindly add `unit specs` for this `update_post_comments_counter` method as well :+1:

2023-08-19 20:30 UTC, aamirkhan2478 requested changes
Hi @Reggeditt, 

![](https://media3.giphy.com/media/RcZlXVml8oKtoGQeqe/giphy.gif?cid=ecf05e47cw5pjd1gapdzk1t3vp0n73caujoqxw3vkcu8ssng&rid=giphy.gif&ct=g)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Highlights
✔️ Good Effort
✔️ Your design is good.
✔️ All linter passed

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-19 20:30 UTC, aamirkhan2478 commented on app/models/post.rb
> +  end
- [ ] As mentioned by the previous reviewer kindly add unit specs for the `update_likes_counter` method as well but still, you didn't add any specs for `update_likes_counter`👍

2023-08-19 22:18 UTC, fobadara approved these changes
Hi @Reggeditt, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![APPRVED](https://user-images.githubusercontent.com/62938735/260206857-3c93f52c-5b21-4f6f-8bc4-be158a13d3cd.gif)

## Highlights
✅ Descriptive README
✅ Descriptive PR summary
✅ Clean code



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-19 22:18 UTC, fobadara commented on spec/models/like_spec.rb
[OPTIONAL] In future you should explain to the reviewer in a comment that you have implemented the requirement. The only difference here is that you named it differently which is allowed in this project.

2023-08-21 11:49 UTC, merged